### ISSUE TITLE
Support for easily changing the texts?

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnitySimpleGDPRConsent#3]
My game is available on multiple languages so I have to translate the consent dialog to other languages, but I couldnt find a way to easily change some of the dialog texts.

Any plans on adding that?

I had to manually do something like:
`GameObject.Find("TermsView/Title").GetComponent<Text>().text = ....
GameObject.Find("TermsView/Introduction").GetComponent<Text>().text = ....`

**Comment by yasirkula** [comment]
Most localizatioin plugins offer components that can be attached to Text objects and automatically translate them. I think you can add such components to those Texts in GDPRConsentCanvas.prefab.

**Comment by rotter** [comment]
Makes sense! I created the localization solution myself and didnt think about that when creating it, so my solution doesnt work like that, but I guess your answer will apply to most other users, so dont worry about it, thanks anyway!
