### ISSUE TITLE
Exception when get_IsGDPRApplicable

### ISSUE THREAD

**Issue by programming2012** [yasirkula/UnitySimpleGDPRConsent#4]
Exception when get_IsGDPRApplicable

**Reproduction steps**
When game startup, I call SimpleGDPR.IsGDPRApplicable in Unity's Start() method. And then get the following Exception.

- Unity version:2019.2.2f1
- Platform: iOS
- Device:iPhone8,1(2020-08-25);iPhone12,3(2020-08-20);iPad4,1(2020-08-19); and other iPhone iPad Device
- How did you download the plugin: GitHub

**Additional info**
The tversion of UnitySimpleGDPRConsent is V1.0.0 in my app. 
Today, i will update to V1.1.0.

Exception
SocketException: Connection refused
System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.InitConnection (System.Net.HttpWebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.<SendRequest>b__41_0 (System.Object o) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
Rethrow as WebException: Error: ConnectFailure (Connection refused)
System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream, System.Net.CompletionDelegate completionDelegate, System.ComponentModel.AsyncOperation asyncOp) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadString (System.Uri address) (at <00000000000000000000000000000000>:0)
SimpleGDPR.get_IsGDPRApplicable () (at <00000000000000000000000000000000>:0)

====================================================================================

Exception
WebException: The remote server returned an error: (403) Access Denied.
System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) (at <00000000000000000000000000000000>:0)
System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) (at <00000000000000000000000000000000>:0)
System.AsyncCallback.Invoke (System.IAsyncResult ar) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
SimpleGDPR:get_IsGDPRApplicable()

====================================================================================

Exception
SocketException: The requested address is not valid in this context
System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.InitConnection (System.Net.HttpWebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebConnection.<SendRequest>b__41_0 (System.Object o) (at <00000000000000000000000000000000>:0)
System.Threading.WaitCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ContextCallback.Invoke (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
Rethrow as WebException: Error: ConnectFailure (The requested address is not valid in this context)
System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream, System.Net.CompletionDelegate completionDelegate, System.ComponentModel.AsyncOperation asyncOp) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) (at <00000000000000000000000000000000>:0)
System.Net.WebClient.DownloadString (System.Uri address) (at <00000000000000000000000000000000>:0)
SimpleGDPR.get_IsGDPRApplicable () (at <00000000000000000000000000000000>:0)

====================================================================================

**Comment by yasirkula** [comment]
IsGDPRApplicable is determined by querying [http://adservice.google.com/getconfig/pubvendors](http://adservice.google.com/getconfig/pubvendors). I'd guess that either the device isn't connected to internet or there is an ad blocker installed on device/router that is also blocking that url. This exception is catched by the plugin, so you can ignore it if you wish.

**Comment by programming2012** [comment]
Thanks.
Before call IsGDPRApplicable, I Checked if the network is connected. May be there is an ad blocker installed on device/router
