### ISSUE TITLE
Is it possible to disable access to any privacy-related content without the user's consent?

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnitySimpleGDPRConsent#6]
[汇美婚礼软件.txt](https://github.com/yasirkula/UnitySimpleGDPRConsent/files/8692683/default.txt)
in android，I don't know why, just get privacy as soon as it runs, this is the stack, is it possible to block them
Or defer them until the user agrees?

**Comment by yasirkula** [comment]
TermsOfServiceDialog isn't shown until you call SimpleGDPR.ShowDialog. Perhaps you're calling it in Awake/Start? Also make sure to not drag&drop the GDPRConsentCanvas prefab to your scene, it's instantiated automatically at runtime.

**Comment by ShenKang4181** [comment]
Can this plugin block other plugins or codes that access privacy before the user agrees?

**Comment by yasirkula** [comment]
Unfortunately not. You'll need to initialize them manually after the user gives consent.

**Comment by ShenKang4181** [comment]
ok，i know ~
